# Generated by Django 5.1.2 on 2025-09-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_income_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
