# Generated by Django 5.1.2 on 2025-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_income_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="expense",
            name="receipt_image",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
