# Generated by Django 5.1.2 on 2025-09-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_expense_description_alter_expense_receipt_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="currency",
            field=models.CharField(default="INR", max_length=3),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_currency",
            field=models.CharField(blank=True, default="INR", max_length=3, null=True),
        ),
    ]
